<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Image Community</name>
   <tag></tag>
   <elementGuidId>8a1212a2-38bc-4211-9c26-8ec035e816db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div[6]/div/div/div/div/div/div/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>anima-src</name>
      <type>Main</type>
      <value>~/assets/img/community-01.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_nuxt/img/d0fe2f1.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid boxouter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;mobileversion h-auto&quot;]/div[6]/div[1]/div[@class=&quot;row m-0 p-0&quot;]/div[@class=&quot;col-12 px-2 pt-4 m-md-0 p-md-0&quot;]/div[@class=&quot;card-transparent m-0 p-0&quot;]/div[@class=&quot;card-content m-0 p-0&quot;]/div[@class=&quot;card-body  p-0 m-0&quot;]/div[@class=&quot;row communityfield&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row shadow-z-1 boxing&quot;]/div[@class=&quot;col-12 d-block d-sx-none d-sm-block  py-0 px-0 text-right align-middle hidepicture&quot;]/img[@class=&quot;img-fluid boxouter&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div[6]/div/div/div/div/div/div/div/div/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div/div/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
