<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text A1</name>
   <tag></tag>
   <elementGuidId>4c21ce91-5791-458d-8a30-59e79b77d50b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'card-text padding-l-r-b-20' and (contains(text(), '
                • Service 
 Service is the RoomMe.id - Tenant App mobile application operated by RoomMe.id 
 
 • Personal Data 
 Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession). 
 
• Usage Data 
 Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). 
 
 • Cookies 
 Cookies are small files stored on your device (computer or mobile device). 
 
 
              ') or contains(., '
                • Service 
 Service is the RoomMe.id - Tenant App mobile application operated by RoomMe.id 
 
 • Personal Data 
 Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession). 
 
• Usage Data 
 Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). 
 
 • Cookies 
 Cookies are small files stored on your device (computer or mobile device). 
 
 
              '))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-text padding-l-r-b-20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                • Service 
 Service is the RoomMe.id - Tenant App mobile application operated by RoomMe.id 
 
 • Personal Data 
 Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession). 
 
• Usage Data 
 Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). 
 
 • Cookies 
 Cookies are small files stored on your device (computer or mobile device). 
 
 
              </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion-0&quot;)/div[@class=&quot;card-body&quot;]/p[@class=&quot;card-text padding-l-r-b-20&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion-0']/div/p</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Definitions'])[1]/following::p[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[5]/following::p[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information Collection and Use'])[1]/preceding::p[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Data'])[1]/preceding::p[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/p</value>
   </webElementXpaths>
</WebElementEntity>
