<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Close</name>
   <tag></tag>
   <elementGuidId>abd4eeeb-afa7-40ba-9cd6-2920f7772758</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/_nuxt/img/5ccb7fd.svg']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-signup-success___BV_modal_body_']/div/div/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_nuxt/img/5ccb7fd.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-signup-success___BV_modal_body_&quot;)/div[@class=&quot;p-0 p-md-4&quot;]/div[@class=&quot;custom-modal-head&quot;]/button[@class=&quot;btn btn-close btn-secondary&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-signup-success___BV_modal_body_']/div/div/button/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
   </webElementXpaths>
</WebElementEntity>
